# Generated by Django 2.2.7 on 2019-12-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20191204_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
    ]
